# Directory for backups to be saved to
BACKUP_DIRECTORY : D:/Documents/USB Backup/

# Enable to copy drive content as one folder
COPY : Y

# Enable to compress drive content as one zip
ZIP : Y

# Enable to close when finished
# Disable to view times/errors
CLOSE : Y

# Enable to print bell code upon script completion
NOTIFY : Y

# Devices to be backed up
DEVICES :
    # DeviceID : BackupName
    3662415509 : School
    4035802026 : Work
